export interface IUser {
    id: number;
    login_id: string;
    last_name?: any | null;
    first_name?: string | null;
    user_name: string;
    email?: string | null;
    phone?: any | null;
    birthdate?: string | null;
    image?: string | null;
    country?: string | null;
    state?: string | null;
    city?: string | null;
    ps?: string | null;
    zip?: number | null;
    address_1?: string | null;
    address_2?: string | null;
    created_date?: string | null;
    user_type__name: string;
    user_type__view_panel: string;
    user_extend__placement?: any | null;
    reference__id?: number | null;
    reference__last_name?: string | null;
    reference__first_name?: string | null;
    reference__user_name?: string | null;
    reference__email?: string | null;
    reference__phone?: string | null;
    reference__image?: string | null;
    agent__id?: number | null;
    agent__last_name?: string | null;
    agent__first_name?: string | null;
    agent__user_name?: string | null;
    agent__email?: string | null;
    agent__phone?: string | null;
    agent__image?: string | null;
    creator__id?: number | null;
    creator__last_name?: string | null;
    creator__first_name?: string | null;
    creator__user_name?: string | null;
    creator__email?: string | null;
    creator__phone?: string | null;
    creator__image?: string | null;
    parent__id?: number | null;
    parent__last_name?: string | null;
    parent__first_name?: string | null;
    parent__user_name?: string | null;
    parent__email?: string | null;
    parent__phone?: string | null;
    parent__image?: string | null;
}
